-- CREATE QUERY FOR SQL DDL SKILLSETS

-- CREATE NEW DATABASE (SQL SKILLSETS)

CREATE DATABASE GMC_SKILLSETS;

-- CREATE TABLES UNDER THE NEW DATABASE
USE GMC_SKILLSETS;

CREATE TABLE Customers(
	Customer_ID INT PRIMARY KEY, 
	Customer_Name VARCHAR(25) NOT NULL,
	Customer_Tel VARCHAR (15) NOT NULL
);

CREATE TABLE Products(
	Product_ID INT PRIMARY KEY,
	Product_Name VARCHAR(25) NOT NULL,
	Category VARCHAR (25) NOT NULL,
	Product_Price DECIMAL(10,2) NOT NULL CHECK (Product_Price > 0)
);

CREATE TABLE Orders(
	Order_ID INT PRIMARY KEY,
	Quantity INT NOT NULL,
	Order_Date DATE NOT NULL,
	Customer_ID INT FOREIGN KEY REFERENCES Customers(Customer_ID) NOT NULL,
	Product_ID INT FOREIGN KEY REFERENCES Products (Product_ID) NOT NULL,
	Total_Amt DECIMAL(10,2) NOT NULL
);

